# Generated by Django 4.1.7 on 2023-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("fee", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
    ]
