# Generated by Django 4.1.7 on 2023-03-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="purchase_date",
            field=models.IntegerField(default=1679320000),
            preserve_default=False,
        ),
    ]
